

# Preface {-}


## About this book {.unnumbered}

R Shiny Application is a structure for making web applications utilizing R code. It is
planned fundamentally considering information researchers, and keeping that in
mind, you can make pretty confounded Shiny applications with no knowledge about
HTML, CSS, or JavaScript. Then again, Shiny doesn’t restrict you to making
insignificant or pre-assembled applications: its UI segments can be handily modified
or expanded, and its worker utilizes responsive programming to allow you to make
any sort of back-end rationale you need. R Shiny is intended to feel mystically simple
when you’re beginning, but then the further you get into how it functions, the more
you understand it’s worked out of broad structure obstructs that have solid
programming standards behind them.


R Shiny Application is utilized in nearly however many specialties and ventures as R
itself is. It’s utilized in scholarly world as a showing device for measurable ideas, an
approach to get students amped up for figuring out how to compose code, a
sensational mode for flaunting novel factual techniques or models. It’s utilized by
huge pharma organizations to speed cooperation among researchers and examiners
during drug improvement. It utilizes real-time measurement dashboards that fuse
progressed investigation.

## What you will gain {.unnumbered}

You will learn a handful of useful techniques to build the R Shiny Applications. You will learn more about how to apply the real data into your app, uploading and downloading data, creating the UI and practicing of the reactive programming. 


## Prerequisites {.unnumbered}

You should know how to install R, RStudio, R Packages and an account on https://www.shinyapps.io/ to deploy your app. 




# About the Author {.unnumbered}

Loan Kim Robinson (<https://loankimrobinson.com>) is a Scientific Research Specialist at Bristol Myers Squibb (<https://www.bms.com>). BMS is one of the largest BioTech company on the world. She has earned her MS from the Department of Statistics, at San Diego State University.

She is interested in interactive statistical graphics, statistical computing and
modeling. She is a highly analytical and solution-oriented professional with 7+ years
of demonstrated success in statistical analysis and presentation, hands-on
experience working with patient, biotechnology, and pharmaceutical drug data. She is
successful in driving best-in-class visualization and reporting, as well as, explaining
statistical methods to non-statistical people that results in effective understanding,
cost savings, and efficiency. She also has experience with working across different
levels of leadership to leverage statistical testing, business intelligence, and data-
driven analytics.


Her favorite programming languages are R and Python, she developed many R shiny
applications at her previous and current work. You can find all of her applications
here.


She was born in Ho Chi Minh City, Vietnam, and emigrated to the United States in
2008 with a mere 3 dollars in her pocket, barely enough to buy a sandwich. She is the
embodiment of tenacity and determination, having overcome untold obstacles and
struggles with incredible perseverance. 7 years later, she earned her MS in Statistics.
From there, she worked tirelessly and passionately to become an expert in various
fields of Statistics, Mathematics, Business Intelligence and Data Science to achieve
her dream that few, with far more advantages, could ever hope to achieve.

**_Publications_**

Förger F, Bandoli G, Luo Y, Robinson L, Johnson DL, Chambers CD. Effect of
discontinuing TNF inhibitors during pregnancy on the course of rheumatoid arthritis
and juvenile idiopathic arthritis. Ann Rheum Dis. 2018;77(Suppl 2):604. Presented at
the Annual European Congress of Rheumatology, EULAR. Amsterdam, Netherlands,
June 2018. (Poster).https://ard.bmj.com/content/77/Suppl_2/604.1.info


J. F. Smith, Chelsey and Jones, Ken and L. Johnson, Diana and Bandoli, Gretchen
and K. Robinson, Loan and Kavanaugh, Arthur and Chambers, Christina. Risk of
infantile hemangiomas in the offspring of women with autoimmune disease and the
pathogenic implications of these lesions. American Journal of Medical Genetics Part
A.http://dx.doi.org/10.1002/ajmg.a.38594
